#!/usr/bin/env bash

info=$(cmus-remote -Q 2> /dev/null)

if [ "$?" -ne 0 ]; then
  echo ""
  exit 0
fi

status=$(echo "$info" | grep "^status " | cut -d " " -f 3)
artist=$(echo "$info" | grep "^file " | cut -d "/" -f 6)

if [ "$status" == "stopped" ]; then
  echo ""
  exit 0
fi

echo "$icon ${artist}"
