;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        evil-backward-char
        evil-delete
        evil-exit-emacs-state
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        helm-M-x
        keyboard-escape-quit
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        evil-next-line
        evil-previous-line
        iedit-switch-to-mc-mode
        mouse-set-region
        ))
